# Generated by Django 4.1.3 on 2022-11-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passw',
            field=models.CharField(default=123456, max_length=200),
            preserve_default=False,
        ),
    ]
